package com.rrx.coretransport

import org.junit.Assert.assertEquals
import org.junit.Test
import java.util.UUID

class Rrx1CodecTest {

    @Test
    fun `crc8Atm matches the real backend implementation`() {
        // crc8_atm(b"HELLO") from backend/app/services/sms_protocol.py.
        assertEquals(0x35, Rrx1Codec.crc8Atm("HELLO".toByteArray(Charsets.US_ASCII)))
    }

    @Test
    fun `encode matches encode_rrx1() byte for byte -- vector 1`() {
        // Generated by calling the real Python encode_rrx1() directly,
        // not hand-derived.
        val msg = Rrx1Codec.encode(
            alertUuid = UUID.fromString("9c1f7d3e-5b2a-4f18-9e77-2a4b6c8d0e11"),
            lat = 12.91845,
            lon = 80.22456,
            occurredAtEpochSeconds = 1786712531L,
            severity = "SEVERE",
            speedKmh = 68.4,
            headingDeg = 142.0,
            gpsAccuracyM = 8.0,
            peakG = 9.1,
            rollover = false,
            stillMoving = false,
            unresponsive = false,
            cancelWindowExpired = true,
        )
        assertEquals("RRX1|KGFQTFJV597HH|1291845|8022456|1786712531|3|68|142|8|91|C|57", msg)
    }

    @Test
    fun `encode matches encode_rrx1() byte for byte -- vector 2, all flags plus negative coordinates`() {
        val msg = Rrx1Codec.encode(
            alertUuid = UUID.fromString("00000000-0000-0000-0000-000000000001"),
            lat = -33.86785,
            lon = 151.20732,
            occurredAtEpochSeconds = 1767225600L,
            severity = "CRITICAL",
            speedKmh = 0.0,
            headingDeg = 0.0,
            gpsAccuracyM = 50.0,
            peakG = 0.0,
            rollover = true,
            stillMoving = true,
            unresponsive = true,
            cancelWindowExpired = false,
        )
        assertEquals("RRX1|0000000000000|-3386785|15120732|1767225600|4|0|0|50|0|RMU|D9", msg)
    }
}
