"""Initial schema -- PRD §9, transcribed directly from the DDL there.

Hand-written rather than autogenerated: the DDL is already fully specified
in PRD.md, and letting autogenerate diff an empty database against the
models would produce equivalent but harder-to-review output for a schema
this size. Every table/index name matches PRD §9 exactly so the two stay
comparable line-for-line.

Revision ID: 0001
Revises:
Create Date: 2026-08-17
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

ALERT_CHANNEL = postgresql.ENUM("DATA", "SMS", "MANUAL_SOS", name="alert_channel")
ALERT_SEVERITY = postgresql.ENUM("MINOR", "MODERATE", "SEVERE", "CRITICAL", name="alert_severity")
ALERT_STATUS = postgresql.ENUM(
    "DETECTED", "CONFIRMED", "CANCELLED", "SENT", "RECEIVED",
    "ENRICHED", "DISPATCHED", "ACKNOWLEDGED", "CLOSED", "FAILED",
    name="alert_status",
)


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # Enum types created explicitly (create_type=False on the columns below)
    # so each is created exactly once, rather than relying on Alembic's
    # implicit per-column enum-creation, which orders unpredictably when the
    # same enum is reused across multiple tables (alert_status appears on
    # both `alerts` and `alert_events`).
    ALERT_CHANNEL.create(bind, checkfirst=True)
    ALERT_SEVERITY.create(bind, checkfirst=True)
    ALERT_STATUS.create(bind, checkfirst=True)

    # ============ Devices & users ============
    op.create_table(
        "devices",
        sa.Column("device_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("device_hash", sa.Text, nullable=False, unique=True),
        sa.Column("model", sa.Text),
        sa.Column("android_version", sa.Text),
        sa.Column("app_version", sa.Text),
        sa.Column("locale", sa.Text, nullable=False, server_default="en-IN"),
        sa.Column("msisdn_hash", sa.Text),
        sa.Column("registered_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("last_seen_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("consent_flags", postgresql.JSONB, nullable=False, server_default="{}"),
    )

    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("device_id", postgresql.UUID(as_uuid=True),
                 sa.ForeignKey("devices.device_id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("msisdn_enc", sa.LargeBinary, nullable=False),
        sa.Column("relation", sa.Text),
        sa.Column("priority", sa.SmallInteger, nullable=False, server_default="1"),
    )

    # ============ Road network ============
    op.create_table(
        "road_segments",
        sa.Column("segment_id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("osm_way_id", sa.BigInteger),
        sa.Column("geom", geoalchemy2.Geometry("LINESTRING", srid=4326, spatial_index=False), nullable=False),
        sa.Column("length_m", sa.REAL, nullable=False),
        sa.Column("road_class", sa.Text),
        sa.Column("lanes", sa.SmallInteger),
        sa.Column("speed_limit_kmh", sa.SmallInteger),
        sa.Column("curvature_deg", sa.REAL),
        sa.Column("gradient_pct", sa.REAL),
        sa.Column("is_lit", sa.Boolean),
        sa.Column("is_urban", sa.Boolean),
        sa.Column("junction_count", sa.SmallInteger),
        sa.Column("h3_r5", sa.Text, nullable=False),
        sa.Column("district", sa.Text),
        sa.Column("state", sa.Text),
    )
    op.create_index("road_segments_geom_gix", "road_segments", ["geom"], postgresql_using="gist")
    op.create_index("road_segments_h3_idx", "road_segments", ["h3_r5"])

    op.create_table(
        "historical_crashes",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("geom", geoalchemy2.Geometry("POINT", srid=4326, spatial_index=False), nullable=False),
        sa.Column("segment_id", sa.BigInteger, sa.ForeignKey("road_segments.segment_id")),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("severity", sa.Text),
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("raw", postgresql.JSONB),
    )
    op.create_index("historical_crashes_geom_gix", "historical_crashes", ["geom"], postgresql_using="gist")

    op.create_table(
        "blackspots",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("geom", geoalchemy2.Geometry("LINESTRING", srid=4326, spatial_index=False), nullable=False),
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("designated_on", sa.Date),
        sa.Column("fatal_count", sa.SmallInteger),
        sa.Column("notes", sa.Text),
    )

    # ============ Alerts ============
    op.create_table(
        "alerts",
        sa.Column("alert_uuid", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("device_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("devices.device_id")),
        sa.Column("channel", postgresql.ENUM(name="alert_channel", create_type=False), nullable=False),
        sa.Column("status", postgresql.ENUM(name="alert_status", create_type=False), nullable=False),
        sa.Column("severity", postgresql.ENUM(name="alert_severity", create_type=False), nullable=False),
        sa.Column("geom", geoalchemy2.Geometry("POINT", srid=4326, spatial_index=False), nullable=False),
        sa.Column("gps_accuracy_m", sa.REAL),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("speed_kmh", sa.REAL),
        sa.Column("heading_deg", sa.REAL),
        sa.Column("peak_g", sa.REAL),
        sa.Column("delta_v_kmh", sa.REAL),
        sa.Column("impact_direction", sa.Text),
        sa.Column("rollover", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("still_moving", sa.Boolean),
        sa.Column("segment_id", sa.BigInteger, sa.ForeignKey("road_segments.segment_id")),
        sa.Column("landmark", sa.Text),
        sa.Column("conditions", postgresql.JSONB),
        sa.Column("risk_score", sa.REAL),
        sa.Column("risk_band", sa.Text),
        sa.Column("model_a_version", sa.Text),
        sa.Column("model_b_version", sa.Text),
        sa.Column("is_simulated", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("has_trace", sa.Boolean, nullable=False, server_default="false"),
    )
    op.create_index("alerts_geom_gix", "alerts", ["geom"], postgresql_using="gist")
    op.create_index("alerts_received_idx", "alerts", [sa.text("received_at DESC")])

    op.create_table(
        "alert_events",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("alert_uuid", postgresql.UUID(as_uuid=True),
                 sa.ForeignKey("alerts.alert_uuid", ondelete="CASCADE"), nullable=False),
        sa.Column("status", postgresql.ENUM(name="alert_status", create_type=False), nullable=False),
        sa.Column("at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("actor", sa.Text),
        sa.Column("detail", postgresql.JSONB),
    )

    op.create_table(
        "sensor_traces",
        sa.Column("alert_uuid", postgresql.UUID(as_uuid=True),
                 sa.ForeignKey("alerts.alert_uuid", ondelete="CASCADE"), primary_key=True),
        sa.Column("sample_hz", sa.SmallInteger, nullable=False),
        sa.Column("payload", sa.LargeBinary, nullable=False),
        sa.Column("label", sa.Text),
    )

    # ============ Dispatch (simulated in v1) ============
    op.create_table(
        "dispatches",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("alert_uuid", postgresql.UUID(as_uuid=True), sa.ForeignKey("alerts.alert_uuid"), nullable=False),
        sa.Column("gateway", sa.Text, nullable=False),
        sa.Column("is_simulated", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("external_ticket_id", sa.Text),
        sa.Column("responder_unit_id", sa.BigInteger),
        sa.Column("request_payload", postgresql.JSONB, nullable=False),
        sa.Column("response_payload", postgresql.JSONB),
        sa.Column("latency_ms", sa.Integer),
        sa.Column("requested_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("acknowledged_at", sa.TIMESTAMP(timezone=True)),
    )

    op.create_table(
        "responder_units",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("kind", sa.Text, nullable=False),
        sa.Column("geom", geoalchemy2.Geometry("POINT", srid=4326, spatial_index=False), nullable=False),
        sa.Column("capacity", sa.SmallInteger),
        sa.Column("is_seeded", sa.Boolean, nullable=False, server_default="true"),
    )
    op.create_index("responder_units_geom_gix", "responder_units", ["geom"], postgresql_using="gist")

    # ============ Risk ============
    op.create_table(
        "risk_evaluations",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("segment_id", sa.BigInteger, sa.ForeignKey("road_segments.segment_id"), nullable=False),
        sa.Column("evaluated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("hour_bucket", sa.SmallInteger, nullable=False),
        sa.Column("risk_score", sa.REAL, nullable=False),
        sa.Column("risk_band", sa.Text, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column("top_factors", postgresql.JSONB),
        sa.Column("model_version", sa.Text, nullable=False),
    )
    op.create_index("risk_eval_seg_time_idx", "risk_evaluations",
                    ["segment_id", sa.text("evaluated_at DESC")])

    op.create_table(
        "risk_baseline",
        sa.Column("segment_id", sa.BigInteger, sa.ForeignKey("road_segments.segment_id"), primary_key=True),
        sa.Column("hour_bucket", sa.SmallInteger, primary_key=True),
        sa.Column("base_score", sa.REAL, nullable=False),
        sa.Column("model_version", sa.Text, nullable=False),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "weather_observations",
        sa.Column("h3_r5", sa.Text, primary_key=True),
        sa.Column("observed_at", sa.TIMESTAMP(timezone=True), primary_key=True),
        sa.Column("source", sa.Text, primary_key=True),
        sa.Column("temp_c", sa.REAL),
        sa.Column("precip_mm_h", sa.REAL),
        sa.Column("visibility_m", sa.Integer),
        sa.Column("wind_kmh", sa.REAL),
        sa.Column("humidity_pct", sa.REAL),
        sa.Column("condition_code", sa.Text),
    )

    op.create_table(
        "traffic_observations",
        sa.Column("segment_id", sa.BigInteger, sa.ForeignKey("road_segments.segment_id"), primary_key=True),
        sa.Column("observed_at", sa.TIMESTAMP(timezone=True), primary_key=True),
        sa.Column("current_kmh", sa.REAL),
        sa.Column("freeflow_kmh", sa.REAL),
        sa.Column("confidence", sa.REAL),
    )


def downgrade() -> None:
    for t in ("traffic_observations", "weather_observations", "risk_baseline", "risk_evaluations",
             "responder_units", "dispatches", "sensor_traces", "alert_events", "alerts",
             "blackspots", "historical_crashes", "road_segments",
             "emergency_contacts", "devices"):
        op.drop_table(t)
    bind = op.get_bind()
    ALERT_STATUS.drop(bind, checkfirst=True)
    ALERT_SEVERITY.drop(bind, checkfirst=True)
    ALERT_CHANNEL.drop(bind, checkfirst=True)
